apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-claim
  labels:
    name: grafanapvcclaim
spec: 
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 2Gi