apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc-claim
  labels:
    name: prometheuspvcclaim
spec: 
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 2Gi