apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090	
      nodePort: 30001
  type: NodePort
  selector:
    app: prometheus